---
title: "YOUR-TITLE"
date: YYYY-MM-DD
---
title: first
author: Victor Zyryanov
email: VooooooZ@ya.ru
description: > # this means to ignore newlines until "baseurl:"
  Сайт о программировании
# social links
vk_username: https://vk.com/club125101912
github_username:  your-github-handle
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
